# Site wide configuration

title: Adekunle A. Ajibode
locale: en_US
logo: # filename of a logo image that has been placed into your images directory

# Enter the following platform usernames if you would like for them to appear on your site.
owner:
  name: Adekunle A. Ajibode
  avatar: Newpix.jpg
  bio: "My expertise lies in utilizing Data Mining techniques to address research inquiries in various domains such as Software Engineering, Education, and Health Care. The majority of my Data Mining research replication packages are accessible on both my Bitbucket and GitHub profiles, while other Research replication packages specific to Software Engineering can be found solely on my GitHub profile. Additionally, all my published papers are freely available on several academic platforms, including Google Scholar and ResearchGate, as well as other libraries.
Outside academics and research, I am seeking a position as an IT support specialist, Technical support specialist, IT technician, or a similar role where I can apply my technical skills, problem-solving abilities, and strong customer service orientation to effectively assist users with their IT needs."
  email: damajibode@gmail.com
  # Do not include the @ symbol in your Twitter username
  twitter: AjibodeAdekunle
  linkedin: eyinlojuoluwa
  github: eyinlojuoluwa
  orcid: 0000-0002-9212-4566 (ex. 0000-0000-0000-0000)
  researchgate: Adekunle-Ajibode
  mendeley: #username
  google:
    plus: #username
    analytics:
    verify:
    scholar: https://scholar.google.com/citations?user=JoJ2ycAAAAAJ&hl=en&oi=ao #id
  facebook: Eyinlojuoluwa
  instagram: ilerieyinlojuoluwa
  bing-verify:
  stackoverflow: 11442522/eyinlojuoluwa
  xing: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
  disqus-shortname:

# The following adjust the accents for your site. If you would like to further edit colors, fonts, font sizes, etc.
# you may do so in _sass/variables.scss
highlight-color: '#CC0000'
lowlight-color: '#000'

  # NOTE: If you would like your site to be licensed under a creative commons license, uncomment the 'yes' next to the type of license you wish to use.
creative-commons:
  cc-by: #yes
  cc-by-nc: yes

#DO NOT EDIT BEYOND THIS POINT
# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
